---
version: '3.7'
services:
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile.busybox
    image: defectdojo/defectdojo-busybox:${NGINX_VERSION:-latest}
  uwsgi:
    entrypoint: ['/wait-for-it.sh', '34.69.250.196:5432', '-t', '30', '--', '/entrypoint-unit-tests-devDocker.sh']
    volumes:
      - '.:/app:z'
    environment:
      DD_DEBUG: 'True'
      DD_TEST_DATABASE_NAME: ${DD_TEST_DATABASE_NAME:-test_defectdojo}
      DD_DATABASE_NAME: ${DD_TEST_DATABASE_NAME:-test_defectdojo}
  celerybeat:
    environment:
      DD_DATABASE_URL: ${DD_TEST_DATABASE_URL:-postgres://root:root@34.69.250.196:5432/test_defectdojo}
  celeryworker:
    environment:
      DD_DATABASE_URL: ${DD_TEST_DATABASE_URL:-postgres://root:root@34.69.250.196:5432/test_defectdojo}
  initializer:
    environment:
      DD_INITIALIZE: 'false'
  postgres:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      postgres_DATABASE: ${DD_TEST_DATABASE_NAME:-test_defectdojo}
    volumes:
       - defectdojo_data_unittest:/var/lib/postgres
volumes:
  defectdojo_data_unittest: {}
