{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-initializer
  labels:
    defectdojo.org/component: initializer
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
spec:
  ttlSecondsAfterFinished: {{ .Values.initializerKeepSeconds }}
  template:
    metadata:
      labels:
        defectdojo.org/component: initializer
        app.kubernetes.io/name: {{ include "defectdojo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: initializer
        image: "{{ template "initializer.repository" . }}:{{ .Values.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - /entrypoint-initializer.sh
        envFrom:
        - configMapRef:
            name: {{ $fullName }}
        - secretRef:
            name: {{ $fullName }}
        env:
        - name: DD_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              {{- if eq .Values.database "postgresql" }}
              # use postgresql chart secret
              # name: {{- if .Values.postgresql.enabled }} {{ $fullName }}-{{ .Values.database }} {{- else }} {{ .Values.postgresql.existingSecret }} {{- end }}
              # Use secret handled outside of the chart
              name: {{- if .Values.postgresql.enabled }} defectdojo-postgresql-specific {{- else }} {{ .Values.postgresql.existingSecret }} {{- end }}
              key: postgresql-password
              {{- else if eq .Values.database "postgres" }}
              # Use postgres chart secret
              # name: {{- if .Values.postgres.enabled }} {{ $fullName }}-{{ .Values.database }} {{- else }} {{ .Values.postgres.postgresPasswordSecret }} {{- end }}
              # Use secret handled outside of the chart
              name: {{- if .Values.postgres.enabled }} defectdojo-postgres-specific {{- else }} {{ .Values.postgres.postgresPasswordSecret }} {{- end }}
              key: postgres-password
              {{- end }}
        resources:
          {{- toYaml .Values.initializer.resources | nindent 10 }}
      restartPolicy: Never
      {{- with .Values.initializer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 1
