{{- if .Values.createpostgresSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo-postgres-specific
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  postgres-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}

{{- end }}
